### PR TITLE
fix: add eshe_instructor to allowedRoles [BB-7489]

### PR DESCRIPTION
**Pull request by 0x29a**
Port of https://github.com/0x29a/frontend-app-gradebook/pull/1 to Palm.

### CODE REVIEW

**Comment by Agrendalath** [comment]
@0x29a, can we rename this branch from `opencraft-release/palm.1` to `opencraft-release/palm.1-eshe`? This change is specific to the client, so we don't want anyone else to use it.

I'm asking because I just pushed the `opencraft-release/palm.1-echo` branch, which includes the `@edx/frontend-platform` version bump from `2.5.0` to `^4.2.0`. An older version of the `@edx/frontend-platform` breaks the deployment when using a custom header/footer for the MFEs. Therefore, I considered calling that branch `opencraft-release/palm.1` instead so everyone can use it.

**Comment by 0x29a** [comment]
@Agrendalath, sure, we can. This feature is gated, so other clients shouldn't notice any changes. We added it to our shared branch to avoid having a client-specific branch. Should I create a ticket for the next sprint to extract these changes to a separate branch?

**Comment by Agrendalath** [comment]
@0x29a, ah, thanks for clarifying. If the `allowedRoles` are not visible anywhere in this MFE (outside of the source code), it's OK to keep it as-is.

**Comment by 0x29a** [comment]
@Agrendalath, yep, `allowedRoles` is used only to allow or block access to the gradebook depending on roles that some particular user posses.

**Pull request merged**
