### PR TITLE
fix: add limited_staff to allowedRoles [BB-7834]

### PR DESCRIPTION
**Pull request by 0x29a**
Backported from [here](https://github.com/openedx/frontend-app-gradebook/pull/352).

### CODE REVIEW

**Comment by Agrendalath** [comment]
@0x29a, the change looks good to me, but I need to check something first, so I'll review this next week.

We cannot use the `opencraft-release/palm.1` for this client because it uses `@edx/frontend-platform v2.5.0`, incompatible with a custom header component in Palm. Therefore, I created [the `opencraft-release/palm.1-echo` branch](opencraft-release/palm.1-echo) for them, which includes ae1702d182ae41e462b1b6657cabd1758cbb8f9e (that bumps @edx/frontend-platform version from 2.5.0 to ^4.2.0). Our `opencraft-release/palm.1` does not have these changes, but it contains the cherry-picked 3644172d9471ed3299a9b5accece072b99a7582a. Therefore, I created [opencraft-release/palm.1-echo-2](https://github.com/open-craft/frontend-app-gradebook/commits/opencraft-release/palm.1-echo-2), which includes all commits up to 3be81e02ea2509e19f711bd9ca50f80cf31f316d. I'll be deploying it to the client instance to test it. Then, I'd like to rebase our `opencraft-release/palm.1` branch onto it.

Could it cause any trouble for the other client that uses this repo?

**Comment by 0x29a** [comment]
>Could it cause any trouble for the other client that uses this repo?

@Agrendalath, I'm not that involved in the frontend development for this client, but I don't think it has any customizations that would conflict with the changes you're going to add.

@navinkarkera, do you know if bumping @edx/frontend-platform version from 2.5.0 to ^4.2.0 (https://github.com/open-craft/frontend-app-gradebook/commit/ae1702d182ae41e462b1b6657cabd1758cbb8f9e) in the gradebook MFE can break something for ASU?

**Comment by navinkarkera** [comment]
@0x29a Unfortunately, I don't know.

**Comment by Agrendalath** [comment]
cc: @viadanna, as the client owner ^

**Comment by viadanna** [comment]
I don't see a problem :+1:

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: checked that the limited staff role can access gradebook
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Comment by Agrendalath** [comment]
I replaced the branches as described above. The original `opencraft-release/palm.1` is now `opencraft-release/palm.1-asu-backup`.

**Pull request merged**
